version: '3'

services:
  postgres:
    # база данных
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - '1234:3000'
    networks:
      # внутреняя сеть
      my_network:
        ipv4_address: 192.168.1.10
    environment:
      # переменные
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=42304230
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/16/bin
      - PGDATA=/var/lib/postgresql/data
    volumes:
      # папки
      - "./volumes/postgresql:/var/lib/postgresql"
      - "./volumes/postgresql_data:/var/lib/postgresql/data"

  sonarqube:
    # сканер
    image: sonarqube
    container_name: sonar
    hostname: sonar
    user: sonarqube
    working_dir: /opt/sonarqube
    ports:
      - 9000:9000
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=42304230
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - JAVA_HOME=/opt/java/openjdk
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - JAVA_VERSION=jdk-17.0.9+9
      - DOCKER_RUNNING=true
      - SONARQUBE_HOME=/opt/sonarqube
      - SONAR_VERSION=10.3.0.82913
      - SQ_DATA_DIR=/opt/sonarqube/data
      - SQ_EXTENSIONS_DIR=/opt/sonarqube/extensions
      - SQ_LOGS_DIR=/opt/sonarqube/logs
      - SQ_TEMP_DIR=/opt/sonarqube/temp
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Dnode.store.allow_mmap=false
    volumes:
      - "./volumes/sonarqube_data:/opt/sonarqube/data"
      - "./volumes/sonarqube_extensions:/opt/sonarqube/extensions"
      - "./volumes/sonarqube_logs:/opt/sonarqube/logs"
    networks:
      my_network:
        ipv4_address: 192.168.1.11
    runtime: runc

networks:
  # настройка внутренней сети
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24 # конфигурация маски внутренней сети
